drift_detector:
  name: cade

sample_selector:
  name: random

memory_manager:
  name: fixed
  max_size: 500

anti_forgetting:
  name: gpm
  threshold: 0.97

anomaly_scorer:
  name: cade_mad

label_budget: 100
lr: 0.001
n_tasks: 5
dataset: unswnb15
