drift_detector:
  name: ddm

sample_selector:
  name: random

memory_manager:
  name: cndids
  mode: fifo
  capacity: 1000

anti_forgetting:
  name: cndids

anomaly_scorer:
  name: pca

label_budget: 0
lr: 0.001
n_tasks: 5
dataset: nslkdd
