drift_detector:
  name: ssf
  drift_threshold: 0.05

sample_selector:
  name: ssf
  mask_threshold: 0.5

memory_manager:
  name: ssf
  max_size: 1000
  num_labeled_sample: 50

anti_forgetting:
  name: lwf_ssf
  lwf_lambda: 0.5

anomaly_scorer:
  name: pca

label_budget: 50
lr: 0.001
n_tasks: 5
dataset: nslkdd
